default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fight_selector_development

test: &test
  <<: *default
  database: fight_selector_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: fight_selector_production

cucumber:
  <<: *test
